# +++ TRAVIS-FILE for https://github.com/h-da/geli +++

# required for chrome to install
dist: trusty
# required for e2e tests to complete succesfully (page crash???)
sudo: required
language: node_js
node_js:
  - "7"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      # manually update dependencies for chrome
      - libfontconfig1
      - libstdc++6
      - lsb-base
      # used for frontend e2e tests
      - google-chrome-stable

services:
  - mongodb

branches:
  only:
    # - master
    - develop
    # Only for dev 
    - feature/00-coveralls
    - feature/14-travis-new

cache:
  directories:
    - api/node_modules
    - app/webFrontend/node_modules

before_script:
  # required for chrome to start properly
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  # install api and return back to root for following steps
  - cd api
  - npm install
  # install travis specific stuff
  - npm install coveralls nlf # mocha-lcov-reporter
  - cd ..
  # install frontend and return back to root for following steps
  - cd app/webFrontend
  - npm install
  - cd ../..

script:
  # run backend-tests and return back to root for following steps
  - cd api 
  # - npm run tslint      # run linter | included in command test
  - npm run test        # run backend test
  - cd ..
  # run frontend-tests and return back to root for following steps
  # npm scripts won't work here (dunno why...)
  - cd app/webFrontend
  - npm run lint        # run linter
    # - npm run e2e         # run end-to-end-tests
    # - npm run test        # run test - does not work properly
  - cd ../..

after_script:
  # send backend covarage report to coveralls and return back to root for following steps
  - cd api
  - cat ./coverage/lcov.info
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js -v
  - cd ..
  # run nlf to check licensing
  - cd api
  - ./node_modules/nlf/bin/nlf-cli.js --csv > ../nlf-licenses.csv
  - cd ../app/webFrontend
    # append frontend licenses to existing csv; we have to skip the first line (header)
  - ../../api/node_modules/nlf/bin/nlf-cli.js --csv | awk '{if(NR>1)print}'  >> ../../nlf-licenses.csv
  - cd ../..
  - echo "name,version,directory,repository,summary,from package.json,from license,from readme"
  - cat nlf-licenses.csv | grep -i "apache" # only print apache licenses
  - cat nlf-licenses.csv
  - cd ..

# Disable for testing
#notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/foobar
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false

