version: "2"
services:
  db:
    image: "mongo:3.4.3"
    volumes:
      - "./persistence:/data/db"

  api:
    image: "hdafbi/geli-api"
    links:
      - "db"

  web-frontend:
    image: "hdafbi/geli-web-frontend"
    ports:
      - "80:80"
    links:
      - "api"
